### ISSUE TITLE
php8 support

### ISSUE THREAD

**Issue by behalp** [chillerlan/php-geojson-helpers#1]
Hello,
do you plan update of this package for php8 support, I get this error when I try update with composer:

```
- Root composer.json requires chillerlan/php-geojson-helpers ^1.0 -> satisfiable by chillerlan/php-geojson-helpers[1.0.0].
- chillerlan/php-geojson-helpers 1.0.0 requires php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.
```

**Comment by codemasher** [comment]
Oh, i almost forgot that this library exists... 😄 Sure i can update it to support PHP 8.

**Comment by behalp** [comment]
great, thank you I dont want switch to some other package becase of this

**Comment by codemasher** [comment]
There you go: https://github.com/chillerlan/php-geojson-helpers/releases/tag/2.0.0

The 2.0 API is basically identical to 1.0, with the addition of the polyline simplifyer. I'm thinking about a 3.0 release that adds the several feature types as individual classes as well as a `fromJSON` method to allow decoding existing GeoJSON files.
